log syslog all;
debug protocols all;

router id 1.1.1.1;

protocol device {
    scan time 10;
}

protocol direct {
    ipv4;
    ipv6;
    check link yes;
}

protocol kernel fib4 {
    ipv4 {
        import all;
        export all;
    };
}

protocol kernel fib6 {
    ipv6 {
        import all;
        export all;
    };
}

template bgp tmpl_peer_ipv6
{
        local as 55666;
	rr client;
        ipv4
        {
                export all;
                import all;

                next hop self;

                extended next hop on;
        };

        ipv6
        {
                export all;
                import all;

                next hop self;
                extended next hop on;
        };
};

protocol bgp yk1 from tmpl_peer_ipv6 {
        description "YK1";
        direct;
        source address 2401:1700:1:4::2;

        neighbor 2401:1700:1:4::3 as 55666;

        interface "eth1";
}

protocol bgp yk2 from tmpl_peer_ipv6 {
        description "YK2";
        direct;
        source address 2401:1700:1:5::2;

        neighbor 2401:1700:1:5::3 as 55666;

        interface "eth2";
}

protocol bgp yk3 from tmpl_peer_ipv6 {
        description "YK3";
        direct;
        source address 2401:1700:1:6::2;

        neighbor 2401:1700:1:6::3 as 55666;

        interface "eth3";
}
