log syslog all;
debug protocols all;

router id 6.6.6.6;

protocol device {
    scan time 10;
}

protocol direct {
    ipv4;
    ipv6;
    check link yes;
}

protocol kernel fib4 {
    ipv4 {
        import all;
        export all;
    };
}

protocol kernel fib6 {
    ipv6 {
        import all;
        export all;
    };
}

template bgp tmpl_peer_ipv6
{
        local as 55666;
	rr client;
        ipv4
        {
                export all;
                import all;

                next hop self;

                extended next hop on;
        };

        ipv6
        {
                export all;
                import all;

                next hop self;
                extended next hop on;
        };
};

protocol bgp jkt1 from tmpl_peer_ipv6 {
        description "JKT1";
        direct;
        source address 2401:1700:1:a::3;

        neighbor 2401:1700:1:a::2 as 55666;


}
