log syslog all;
debug protocols all;

router id 2.2.2.2;

protocol device {
    scan time 10;
}

protocol direct {
    ipv4;
    ipv6;
    check link yes;
}

protocol kernel fib4 {
    ipv4 {
        import all;
        export all;
    };
}

protocol kernel fib6 {
    ipv6 {
        import all;
        export all;
    };
}

template bgp tmpl_peer_ipv6
{
        local as 55666;
	rr client;
        ipv4
        {
                export all;
                import all;

                next hop self;

                extended next hop on;
        };

        ipv6
        {
                export all;
                import all;

                next hop self;
                extended next hop on;
        };
};

protocol bgp dr1 from tmpl_peer_ipv6 {
        description "DR1";
        direct;
        source address 2401:1700:1:4::3;

        neighbor 2401:1700:1:4::2 as 55666;


}
protocol bgp jkt1 from tmpl_peer_ipv6 {
        description "JKT1";
        direct;
        source address 2401:1700:1:1::3;

        neighbor 2401:1700:1:1::2 as 55666;


}
protocol bgp yk2 from tmpl_peer_ipv6 {
        description "YK2";
        direct;
        source address 2401:1700:1:7::2;

        neighbor 2401:1700:1:7::3 as 55666;


}
protocol bgp yk3 from tmpl_peer_ipv6 {
        description "YK3";
        direct;
        source address 2401:1700:1:8::2;

        neighbor 2401:1700:1:8::3 as 55666;


}
