log syslog all;
debug protocols all;

router id 3.3.3.3;

protocol device {
    scan time 10;
}

protocol direct {
    ipv4;
    ipv6;
    check link yes;
}

protocol kernel fib4 {
    ipv4 {
        import all;
        export all;
    };
}

protocol kernel fib6 {
    ipv6 {
        import all;
        export all;
    };
}

filter ipv4_jkt1_export
{
        if (55666, 1111) ~ bgp_community then {
        accept;
        }

        accept;
}

template bgp tmpl_peer_ipv6
{
        local as 55666;
        rr client;
        ipv4
        {
                export all;
                import all;

                next hop self;

                extended next hop on;
        };

        ipv6
        {
                export all;
                import all;

                next hop self;
                extended next hop on;
        };
};

protocol bgp dr1 from tmpl_peer_ipv6 {
        description "DR1";
        direct;
        source address 2401:1700:1:5::3;

        neighbor 2401:1700:1:5::2 as 55666;

        interface "eth1";
}
protocol bgp jkt1 from tmpl_peer_ipv6 {
        description "JKT1";
        direct;
        source address 2401:1700:1:2::3;

        neighbor 2401:1700:1:2::2 as 55666;

        interface "eth2";
}
protocol bgp yk1 from tmpl_peer_ipv6 {
        description "YK1";
        direct;
        source address 2401:1700:1:7::3;

        neighbor 2401:1700:1:7::2 as 55666;

        interface "eth3";
}
protocol bgp yk3 from tmpl_peer_ipv6 {
        description "YK3";
        direct;
        source address 2401:1700:1:9::2;

        neighbor 2401:1700:1:9::3 as 55666;

        interface "eth4";
}
